//! Writing the app: modules, the router `match`, the `wisp::App` impl.

use super::*;

impl Gen {
    /// The header, then the app's own Rust files, each included into a
    /// module with the prelude, its shims, and the templates it gives data
    /// to; then the shell, the other templates and the JavaScript files.
    pub(super) fn modules(&mut self, p: &Project, web: &Web) -> Result<(), String> {
        self.line(
            0,
            &format!(
                "// @generated by wisp-build for {}. Do not edit.",
                p.root.display()
            ),
        );
        self.line(0, "");
        // Browser modules import the runtime by the version wisp-build gives it.
        self.line(0, &format!(
            "const _: () = assert!(::wisp::rt::same_version({}), \"wisp and wisp-build are different versions: use the same version of both\");",
            lit(crate::runtime_version())
        ));
        self.line(0, "");
        let slots = &p.tree.slots;
        let cuts = &p.tree.intercepts;
        let linked = (p.tree.routes.iter().enumerate()).filter(|(i, _)| {
            !slots.iter().any(|s| s.route == *i) && !cuts.iter().any(|c| c.route == *i)
        });
        self.out.push_str(&typed_routes(linked.map(|r| r.1)));
        match &p.hooks {
            None => self.line(0, "pub mod hooks {}"),
            Some(h) => {
                let rel = p.rel(&h.file);
                let src = crate::read_source(&h.file).map_err(|e| format!("{rel}: {e}"))?;
                self.users = rust_scan::users_table(&src).map_err(|e| format!("{rel}: {e}"))?;
            }
        }
        if let (None, Some(db)) = (&self.users, p.mods.iter().find(|m| m.name == "db")) {
            let src =
                crate::read_source(&db.file).map_err(|e| format!("{}: {e}", p.rel(&db.file)))?;
            self.users = rust_scan::account_table(&src);
        }
        self.db = p.mods.iter().any(|m| m.name == "db");
        // Modules of the app's own (`src/notes.rs`), reachable by name from
        // every route file and as `crate::notes` (see `wisp::app!`).
        self.line(0, "#[doc(hidden)]");
        self.line(0, "pub mod __mods {");
        self.line(1, "#[allow(unused_imports)]");
        self.line(1, "pub use super::routes;");
        for m in &p.mods {
            self.user_mod(m, &p.rel(&m.file), "super::*")?;
            if !m.calls().is_empty() {
                self.call_mod(m, &[]);
            }
            self.line(0, "}");
        }
        self.line(0, "}");
        self.line(0, "");
        self.out.push_str(&crate::render::components(&p.comps));
        // The messages of `t("key")`: of templates, and sent to scripts.
        if let Some(l) = &p.i18n {
            let mut sent = vec![false; p.t_used.len()];
            for k in web.clients.iter().flatten().flat_map(|c| &c.texts) {
                sent[*k] = true;
            }
            self.out.push_str(&l.tables(&p.t_used, &sent));
            self.line(0, "");
        }
        // The sync twins `handle_now` calls, as `module::shim`.
        let twins: Vec<String> = (p.model.routes.iter())
            .flat_map(|r| now_arms(p, r))
            .map(|(s, h)| format!("{}::{}", s.module, h.shim))
            .collect();
        for m in p.hooks.iter().chain(&p.user_mods) {
            self.user_mod(m, &p.rel(&m.file), "super::__mods::*")?;
            self.call_mod(m, &twins);
            for (t, c) in p.templates.iter().zip(&web.clients) {
                if t.user.as_ref().is_some_and(|(u, _)| *u == m.name) {
                    self.template(t, &p.comps, c.as_ref())?;
                }
            }
            self.line(0, "}");
            self.line(0, "");
        }

        self.line(0, "#[doc(hidden)]");
        self.line(0, "pub mod tpl_shell {");
        let [a, b, c] = &p.shell;
        self.line(
            1,
            &format!(
                "pub static S: [&str; 3] = [{}, {}, {}];",
                lit(a),
                lit(b),
                lit(c)
            ),
        );
        self.line(0, "}");
        self.line(0, "");

        for (i, f) in web.js_files.iter().enumerate() {
            let (url, source) = match &f.file {
                Some(file) => (
                    f.path.clone(),
                    format!("include_str!({})", lit(&file.to_string_lossy())),
                ),
                None => (format!("{}?v={}", f.path, f.hash), lit(&f.source)),
            };
            self.line(0, &format!(
                "static __WISP_JS_{i}: ::wisp::ClientModule = ::wisp::ClientModule {{ id: {}, path: {}, url: {}, etag: {}, source: {source}, preload: &[], texts: &[] }};",
                lit(&f.path),
                lit(crate::protocol::unbased(&f.path)),
                lit(&url),
                lit(&format!("\"{}\"", f.hash)),
            ));
        }
        for (t, c) in p.templates.iter().zip(&web.clients) {
            if t.user.is_none() {
                self.template(t, &p.comps, c.as_ref())?;
            }
        }
        Ok(())
    }

    /// A function per page, which runs the loads outermost first and then
    /// renders inside the layouts, and per error page.
    pub(super) fn servers(&mut self, p: &Project) {
        let m = &p.model;
        let layout_load = |l: &&usize| m.layouts[**l].load;
        for (i, (r, route)) in p.tree.routes.iter().zip(&m.routes).enumerate() {
            let Some(pg) = &route.page else {
                continue;
            };
            let page = &p.templates[pg.tpl];
            self.line(0, "#[allow(unused_variables)]");
            self.line(0, &format!("async fn serve_page_{i}(cx: &mut ::wisp::Cx, __o: &mut ::wisp::Out) -> ::wisp::Result<()> {{"));
            if pg.streams {
                self.line(1, "let __aw = ::wisp::rt::Awaits::begin();");
            }
            if p.i18n.is_some() {
                self.line(1, "__o.lang = ::wisp::rt::pick_locale(cx);");
                // The prefix `i18n = ["prefix …"]` asks for, or not.
                if r.has_locale() {
                    self.line(1, "::wisp::rt::locale_redirect(cx)?;");
                }
            }
            for l in route.layouts.iter().filter(layout_load) {
                self.line(
                    1,
                    &format!("let d{l} = layout_{l}::__call::load(cx).await?;"),
                );
            }
            // The slots of the layouts around it, each with its own load.
            for s in p
                .tree
                .slots
                .iter()
                .filter(|s| route.layouts.contains(&s.layout))
            {
                let slot = m.routes[s.route].page.as_ref().expect("a slot is a page");
                if slot.load() {
                    let k = s.route;
                    self.line(1, &format!("let s{k} = page_{k}::__call::load(cx).await?;"));
                }
            }
            let page_load = pg.load();
            if page_load {
                self.line(1, &format!("let d = page_{i}::__call::load(cx).await?;"));
            }
            // A `+page.js` load gets the route and its parameters.
            if page.load_js.is_some() {
                let params: Vec<String> = r
                    .params()
                    .iter()
                    .map(|p| format!("({0}, cx.param({0}))", lit(p)))
                    .collect();
                self.line(
                    1,
                    &format!(
                        "::wisp::rt::live_route(__o, {}, &[{}]);",
                        lit(&r.pattern()),
                        params.join(", ")
                    ),
                );
            }
            if page.stmts.is_some() {
                // The page runs its statements, then hands its render to this
                // closure, which puts it inside the layouts.
                let wrap =
                    p.wrap_layouts(&route.layouts, "__p(__o)".into(), page.t.has_title(), true);
                let end = if pg.streams { "?;" } else { "" };
                self.line(1, &format!(
                    "{}::render(cx, __o, |__o: &mut ::wisp::Out, cx: &::wisp::Cx, __p: &dyn Fn(&mut ::wisp::Out)| {wrap}).await{end}",
                    page.path()
                ));
            } else {
                let data = if page_load { ", &d" } else { "" };
                let inner = format!("{}::render(__o, cx{data})", page.path());
                self.line(1, "let cx: &::wisp::Cx = cx;");
                self.line(
                    1,
                    &format!(
                        "{};",
                        p.wrap_layouts(&route.layouts, inner, page.t.has_title(), true)
                    ),
                );
            }
            if pg.streams {
                self.line(1, "__aw.finish::<App>(cx, __o);");
            }
            if pg.streams || page.stmts.is_none() {
                self.line(1, "Ok(())");
            }
            self.line(0, "}");
            self.line(0, "");
        }

        self.remotes(p);

        // One per +error.wisp, inside the layouts of its directory.
        for (i, e) in m.errors.iter().enumerate() {
            self.line(0, "#[allow(unused_variables)]");
            self.line(0, &format!("async fn serve_error_{i}(cx: &mut ::wisp::Cx, __o: &mut ::wisp::Out, status: u16, message: &str) -> ::wisp::Result<()> {{"));
            for l in e.layouts.iter().filter(layout_load) {
                self.line(
                    1,
                    &format!("let d{l} = layout_{l}::__call::load(cx).await?;"),
                );
            }
            let inner = format!(
                "{}::render(__o, cx, status, message)",
                p.templates[e.tpl].path()
            );
            self.line(1, "let cx: &::wisp::Cx = cx;");
            self.line(
                1,
                &format!(
                    "{};",
                    p.wrap_layouts(&e.layouts, inner, p.templates[e.tpl].t.has_title(), false)
                ),
            );
            self.line(1, "Ok(())");
            self.line(0, "}");
            self.line(0, "");
        }
    }

    /// `#[remote]` functions, at `/_app/r/<hash>`: a path no route has, so
    /// they cost a routed request nothing. Like an action's, a POST's
    /// origin is checked; `before` in hooks.rs has run.
    pub(super) fn remotes(&mut self, p: &Project) {
        if p.remotes.is_empty() {
            return;
        }
        self.line(0, "async fn serve_remote(cx: &mut ::wisp::Cx, __o: &mut ::wisp::Out) -> ::wisp::Result<()> {");
        self.line(1, "use ::wisp::Method::*;");
        self.line(1, "let k = match cx.path() {");
        for (k, r) in p.remotes.iter().enumerate() {
            self.line(2, &format!("{} => {k}, // {}", lit(&r.path()), r.f.name));
        }
        self.line(
            2,
            "_ => return Err(::wisp::Error::new(404, \"Not Found\")),",
        );
        self.line(1, "};");
        self.line(1, "::wisp::rt::endpoint(cx);");
        self.line(1, "let r = match (k, cx.method) {");
        for (k, r) in p.remotes.iter().enumerate() {
            let call = format!("{}::__call::__r_{}(cx).await?", r.module, r.f.name);
            if r.get() {
                self.line(
                    2,
                    &format!("({k}, Get | Head) => ::wisp::rt::remote::get({call}),"),
                );
                self.line(
                    2,
                    &format!(
                        "({k}, _) => return Err(::wisp::rt::method_not_allowed(\"GET, HEAD\")),"
                    ),
                );
            } else {
                self.line(
                    2,
                    &format!("({k}, Post) => {{ ::wisp::rt::check_origin(cx)?; {call} }}"),
                );
                self.line(
                    2,
                    &format!("({k}, _) => return Err(::wisp::rt::method_not_allowed(\"POST\")),"),
                );
            }
        }
        self.line(
            2,
            "_ => return Err(::wisp::Error::new(404, \"Not Found\")),",
        );
        self.line(1, "};");
        self.line(1, "::wisp::rt::respond(__o, r);");
        self.line(1, "Ok(())");
        self.line(0, "}");
        self.line(0, "");
    }

    /// The CSS, and in a release build the static files, embedded. The
    /// scoped `<style>`s go after the app's CSS: in a release build in the
    /// binary, in dev in `.wisp/scoped.css` (see `run`), read with it.
    pub(super) fn assets(&mut self, p: &Project) -> Result<Assets, String> {
        let css = css_source(p.root)?;
        let styles = p.styles();
        let mut files: Vec<(String, PathBuf, String)> = Vec::new();
        let mut text = match &css {
            Some(f) => fs::read(f).map_err(|e| format!("{}: {e}", f.display()))?,
            None => Vec::new(),
        };
        if !styles.is_empty() {
            if !text.is_empty() {
                text.push(b'\n');
            }
            text.extend_from_slice(styles.as_bytes());
        }
        let css_hash = (css.is_some() || !styles.is_empty()).then(|| image::hash(&text));
        if !p.release {
            return Ok(Assets { css_hash, files });
        }
        // With scoped styles the CSS is written out whole, not included.
        let inline = (!styles.is_empty()).then(|| String::from_utf8_lossy(&text).into_owned());
        if let Some(h) = &css_hash {
            let file = css.clone().unwrap_or_else(|| PathBuf::from("app.css"));
            files.push((APP_CSS_PATH.into(), file, h.clone()));
        }
        let found = static_files(p.root)?;
        let paths: Vec<PathBuf> = found.iter().map(|f| f.1.clone()).collect();
        for ((url, f), etag) in found.into_iter().zip(hash_files(&paths)) {
            files.push((url, f, etag?));
        }
        images(p.root, &mut files);
        for (i, (_, file, etag)) in files.iter().enumerate() {
            let ext = file
                .extension()
                .map(|e| e.to_string_lossy().to_ascii_lowercase())
                .unwrap_or_default();
            let body = match &inline {
                Some(t) if i == 0 => format!("{}.as_bytes()", lit(t)),
                _ => format!("include_bytes!({})", lit(&file.to_string_lossy())),
            };
            self.line(0, &format!(
                "static ASSET_{i}: ::wisp::Asset = ::wisp::Asset {{ body: {body}, ext: {}, etag: {} }};",
                lit(&ext),
                lit(&format!("\"{etag}\""))
            ));
        }
        self.line(0, "");
        Ok(Assets { css_hash, files })
    }

    /// The `wisp::App` impl, and the TypeScript client of the endpoints.
    pub(super) fn app(
        &mut self,
        p: &Project,
        web: &Web,
        assets: &Assets,
    ) -> Result<(String, String), String> {
        let css = match &assets.css_hash {
            Some(h) if p.release => Some(h.as_str()),
            Some(_) => Some("dev"),
            None => None,
        };
        let pwa = p.pwa(web, assets, css)?;
        let pwa = pwa.as_ref();
        // Pages the same for every request, with their response heads.
        let baked = p.baked(css, pwa.map_or("", |w| w.head.as_str()));
        for (i, doc) in baked.iter().enumerate() {
            let Some(doc) = doc else { continue };
            let etag = format!("\"{:016x}\"", fnv1a(doc.as_bytes()));
            let head = format!(
                "HTTP/1.1 200 OK\r\ncontent-type: text/html; charset=utf-8\r\netag: {etag}\r\ncontent-length: {}\r\n",
                doc.len()
            );
            self.line(
                0,
                &format!(
                    "static BAKED_{i}: ::wisp::rt::Baked = ::wisp::rt::Baked::new({}, {}, {}); // {}",
                    lit(&head),
                    lit(doc),
                    lit(&etag),
                    p.model.routes[i].pattern
                ),
            );
        }
        if baked.iter().any(Option::is_some) {
            self.line(0, "");
        }
        let pre = self.prerendered(p)?;
        self.line(0, "pub struct App;");
        self.line(0, "");
        self.line(
            0,
            "#[allow(unused_imports, unused_variables, unreachable_patterns)]",
        );
        self.line(0, "impl ::wisp::App for App {");
        self.line(
            1,
            &format!(
                "const ROOT: &'static str = {};",
                lit(&p.root.to_string_lossy())
            ),
        );
        let css = css.map_or("None".into(), |v| format!("Some({})", lit(v)));
        self.line(1, &format!("const CSS: Option<&'static str> = {css};"));
        let tags: Vec<String> = (p.templates.iter())
            .filter_map(|t| Some(lit(&t.t.element.as_ref()?.0)))
            .collect();
        if !tags.is_empty() {
            self.line(
                1,
                &format!(
                    "const ELEMENTS: &'static [&'static str] = &[{}];",
                    tags.join(", ")
                ),
            );
        }
        if let Some(w) = pwa {
            let etag = |s: &str| lit(&format!("\"{:016x}\"", fnv1a(s.as_bytes())));
            let manifest = w.manifest.as_deref();
            self.line(1, &format!(
                "const PWA: Option<::wisp::rt::Pwa> = Some(::wisp::rt::Pwa {{ worker: {}, worker_etag: {}, manifest: {}, manifest_etag: {}, icons: {}, head: {} }});",
                lit(&w.worker),
                etag(&w.worker),
                manifest.map_or("None".into(), |m| format!("Some({})", lit(m))),
                etag(manifest.unwrap_or("")),
                lit(&w.icons),
                lit(&w.head),
            ));
        }
        let mut hashes = shell::hashes(&p.shell);
        hashes.extend(pwa.and_then(|w| w.hash.clone()));
        hashes.extend(p.templates.iter().flat_map(|t| t.t.hashes.iter().cloned()));
        hashes.sort_unstable();
        hashes.dedup();
        if !hashes.is_empty() {
            let all: Vec<String> = hashes.iter().map(|h| lit(h)).collect();
            self.line(
                1,
                &format!(
                    "const SCRIPT_HASHES: &'static [&'static str] = &[{}];",
                    all.join(", ")
                ),
            );
        }
        if !p.md_pages.is_empty() {
            self.line(1, "const PAGES: &'static [::wisp::MdPage] = &[");
            for (path, fields) in md_order(&p.md_pages) {
                let get = |k: &str| fields.iter().find(|(n, _)| n == k).map_or("", |(_, v)| v);
                let all: Vec<String> = (fields.iter())
                    .map(|(k, v)| format!("({}, {})", lit(k), lit(v)))
                    .collect();
                self.line(
                    2,
                    &format!(
                        "::wisp::MdPage {{ path: {}, title: {}, fields: &[{}] }},",
                        lit(path),
                        lit(get("title")),
                        all.join(", ")
                    ),
                );
            }
            self.line(1, "];");
        }
        self.routes(p, assets);
        // Template 0 is the shell.
        let shell = [format!(
            "({}, 0x{:016x})",
            lit("src/app.html"),
            shell::shape(&p.shell)
        )];
        let tpls: Vec<String> = shell
            .into_iter()
            .chain(
                p.templates
                    .iter()
                    .map(|t| format!("({}, 0x{:016x})", lit(&t.rel), t.t.shape)),
            )
            .collect();
        self.line(
            1,
            &format!(
                "const TEMPLATES: &'static [(&'static str, u64)] = &[{}];",
                tpls.join(", ")
            ),
        );
        if let Some(l) = &p.i18n {
            let names: Vec<String> = l.names.iter().map(|n| lit(n)).collect();
            self.line(
                1,
                &format!(
                    "const LOCALES: &'static [&'static str] = &[{}];",
                    names.join(", ")
                ),
            );
            if let Some(langs) = l.html_langs(&p.shell[0]) {
                self.line(1, &langs);
            }
        }
        self.line(0, "");
        self.router(p);
        for l in p.rules.emit() {
            self.line(1, &l);
        }
        let docs = self.api(p)?;
        self.init(p);

        self.line(1, "fn shell() -> [&'static str; 3] {");
        if p.release {
            self.line(2, "tpl_shell::S");
        } else {
            self.line(
                2,
                "[0, 1, 2].map(|i| ::wisp::rt::chunk(0, i, tpl_shell::S[i]))",
            );
        }
        self.line(1, "}");
        self.line(0, "");

        // Asked on every GET before routing: a binary search of the paths,
        // sorted, not a comparison with each.
        self.line(
            1,
            "fn asset(path: &str) -> Option<&'static ::wisp::Asset> {",
        );
        if assets.files.is_empty() {
            self.line(2, "let _ = path;");
            self.line(2, "None");
        } else {
            let mut by_url: Vec<(&str, usize)> = (assets.files.iter())
                .enumerate()
                .map(|(i, (url, _, _))| (url.as_str(), i))
                .collect();
            by_url.sort_unstable();
            let table: Vec<String> = by_url
                .iter()
                .map(|(url, i)| format!("({}, &ASSET_{i})", lit(crate::protocol::unbased(url))))
                .collect();
            self.line(
                2,
                &format!(
                    "static BY_PATH: [(&str, &::wisp::Asset); {}] = [{}];",
                    table.len(),
                    table.join(", ")
                ),
            );
            self.line(
                2,
                "BY_PATH.binary_search_by(|(p, _)| (*p).cmp(path)).ok().map(|i| BY_PATH[i].1)",
            );
        }
        self.line(1, "}");
        self.line(0, "");

        self.line(
            1,
            "fn client_module(path: &str) -> Option<&'static ::wisp::ClientModule> {",
        );
        let modules: Vec<(&Tpl, &Client)> = p
            .templates
            .iter()
            .zip(&web.clients)
            .filter_map(|(t, c)| Some((t, c.as_ref()?)))
            .collect();
        if modules.is_empty() && web.js_files.is_empty() {
            self.line(2, "let _ = path;");
            self.line(2, "None");
        } else {
            self.line(2, "match path {");
            for (t, c) in modules {
                self.line(
                    3,
                    &format!(
                        "{} => Some(&{}::__WISP_CLIENT),",
                        lit(crate::protocol::unbased(&c.path())),
                        t.path()
                    ),
                );
            }
            for (i, f) in web.js_files.iter().enumerate() {
                self.line(
                    3,
                    &format!(
                        "{} => Some(&__WISP_JS_{i}),",
                        lit(crate::protocol::unbased(&f.path))
                    ),
                );
            }
            self.line(3, "_ => None,");
            self.line(2, "}");
        }
        self.line(1, "}");
        self.line(0, "");

        if let Some(mods) = self.types.take().filter(|m| !m.is_empty()) {
            self.line(1, "::wisp::__ts! {");
            self.line(2, "fn types() -> String {");
            self.line(3, "let mut __out = String::new();");
            for m in mods {
                self.line(3, &format!("{m}::__wisp_types(&mut __out);"));
            }
            self.line(3, "__out");
            self.line(2, "}");
            self.line(1, "}");
        }
        // Routes for `wisp build --static`.
        self.line(1, "fn export_routes() -> Vec<::wisp::ExportRoute> {");
        self.line(2, "vec![");
        for r in &p.model.routes {
            let page = r.page.as_ref();
            let actions = page.is_some_and(|pg| pg.actions().next().is_some());
            let entries = match page.filter(|pg| pg.entries()) {
                Some(pg) => format!("Some({}::__call::entries)", pg.module),
                None => "None".into(),
            };
            let ssr = !page.is_some_and(|pg| pg.drawn);
            let prerender = page.is_some_and(|pg| pg.prerender);
            self.line(3, &format!(
                "::wisp::ExportRoute {{ pattern: {}, page: {}, actions: {actions}, server: {}, entries: {entries}, indexed: {}, ssr: {ssr}, prerender: {prerender} }},",
                lit(&r.pattern),
                page.is_some(),
                r.server.is_some(),
                r.indexed
            ));
        }
        self.line(2, "]");
        self.line(1, "}");
        self.line(0, "");

        self.handle(p, &baked, &pre);
        self.handle_now(p);
        self.error(p);
        self.line(0, "}");
        Ok(docs)
    }

    /// The router. A path with no parameter in it is matched whole: by its
    /// length, then by a byte that tells the paths of that length apart,
    /// then by all of it; no other arm that matches the same path comes
    /// before it (see `routes::priority`). The rest are tried in turn, most
    /// specific arm first, each walking the path from its start with byte
    /// prefixes, their parameters slices of it. An arm with a `[...rest]`
    /// matches the path's segments with a slice pattern.
    pub(super) fn router(&mut self, p: &Project) {
        let tree = &p.tree;
        let (whole, parts): (Vec<_>, Vec<_>) = tree
            .arms()
            .into_iter()
            .partition(|(exp, _)| exp.iter().all(|s| matches!(s, Seg::Static(_))));
        self.line(
            1,
            "fn route(path: &str) -> Option<(usize, [&str; ::wisp::rt::MAX_PARAMS])> {",
        );
        if whole.is_empty() && parts.is_empty() {
            self.line(2, "let _ = path;");
            self.line(2, "None");
        }
        if !whole.is_empty() {
            let mut paths: Vec<(String, usize)> = whole
                .iter()
                .map(|(exp, id)| {
                    let mut s: String = exp
                        .iter()
                        .map(|seg| match seg {
                            Seg::Static(x) => format!("/{}", encode_path(x)),
                            _ => unreachable!("partitioned"),
                        })
                        .collect();
                    if s.is_empty() {
                        s.push('/');
                    }
                    (s, *id)
                })
                .collect();
            paths.sort_by(|a, b| a.0.len().cmp(&b.0.len()).then_with(|| a.0.cmp(&b.0)));
            let (open, found) = match parts.is_empty() {
                true => ("", "(@, [\"\"; ::wisp::rt::MAX_PARAMS])"),
                false => ("let whole = ", "@"),
            };
            let arm = |s: &str, id: usize| {
                format!(
                    "(path == {}).then_some({}), // {}",
                    lit(s),
                    found.replace('@', &id.to_string()),
                    tree.routes[id].pattern()
                )
            };
            self.line(2, &format!("{open}match path.len() {{"));
            let mut at = 0;
            while at < paths.len() {
                let len = paths[at].0.len();
                let n = paths[at..]
                    .iter()
                    .take_while(|(s, _)| s.len() == len)
                    .count();
                let bucket = &paths[at..at + n];
                at += n;
                // A byte where each path of the length has its own.
                let tells = (0..len).find(|&i| {
                    let mut b: Vec<u8> = bucket.iter().map(|(s, _)| s.as_bytes()[i]).collect();
                    b.sort_unstable();
                    b.windows(2).all(|w| w[0] != w[1])
                });
                match tells {
                    _ if n == 1 => {
                        let (s, id) = &bucket[0];
                        self.line(3, &format!("{len} => {}", arm(s, *id)));
                    }
                    Some(i) => {
                        self.line(3, &format!("{len} => match path.as_bytes()[{i}] {{"));
                        for (s, id) in bucket {
                            self.line(4, &format!("{} => {}", s.as_bytes()[i], arm(s, *id)));
                        }
                        self.line(4, "_ => None,");
                        self.line(3, "},");
                    }
                    None => {
                        self.line(3, &format!("{len} => match path {{"));
                        for (s, id) in bucket {
                            let found = found.replace('@', &id.to_string());
                            let pattern = tree.routes[*id].pattern();
                            self.line(4, &format!("{} => Some({found}), // {pattern}", lit(s)));
                        }
                        self.line(4, "_ => None,");
                        self.line(3, "},");
                    }
                }
            }
            self.line(3, "_ => None,");
            if parts.is_empty() {
                self.line(2, "}");
            } else {
                self.line(2, "};");
                self.line(2, "if let Some(id) = whole {");
                self.line(3, "return Some((id, [\"\"; ::wisp::rt::MAX_PARAMS]));");
                self.line(2, "}");
            }
        }
        if parts.is_empty() {
            self.line(1, "}");
            self.line(0, "");
            return;
        }
        self.line(2, "const E: &str = \"\";");
        // What follows the path's first `/`; a path without one matches none.
        self.line(2, "let r0 = path.strip_prefix('/')?;");
        for (a, (exp, id)) in parts.into_iter().enumerate() {
            let r = &tree.routes[id];
            let names = r.params();
            let mut values = vec!["E".to_string(); crate::routes::MAX_PARAMS];
            let rest = exp.iter().any(|s| matches!(s, Seg::Rest(_)));
            // A matcher is a guard, so a segment it refuses goes on to the next arm.
            let mut guards = Vec::new();
            let mut guard = |k: usize, m: &Option<String>| {
                let decoded = format!("&::wisp::rt::decode(p{k}.as_bytes(), false)");
                match tree.matchers.iter().find(|(x, _)| Some(x) == m.as_ref()) {
                    Some((m, Some(_))) => {
                        guards.push(format!("param_{m}::__call::matches({decoded})"))
                    }
                    // `locale`: one of `src/locales`.
                    Some((m, None)) if m == "locale" => {
                        let names = p.i18n.as_ref().map_or(&[][..], |l| &l.names[..]);
                        let alts: Vec<String> = names.iter().map(|n| lit(n)).collect();
                        guards.push(match alts.is_empty() {
                            true => "false".into(),
                            false => format!("matches!(p{k}, {})", alts.join(" | ")),
                        })
                    }
                    // `int`: digits that fit a u64, so `parse().unwrap()` holds.
                    Some(_) => guards.push(format!(
                        "p{k}.bytes().all(|b| b.is_ascii_digit()) && p{k}.parse::<u64>().is_ok()"
                    )),
                    None => {}
                }
            };
            let (end, pattern) = (
                format!("return Some(({id}, [@]));"),
                format!("// {}", r.pattern()),
            );
            if rest {
                // The slice pattern of the path's segments, as deep as any.
                let mut pat = Vec::new();
                for (k, seg) in exp.iter().enumerate() {
                    match seg {
                        Seg::Static(s) => pat.push(lit(&encode_path(s))),
                        Seg::Param(n, m) | Seg::Optional(n, m) => {
                            pat.push(format!("p{k}"));
                            values[names.iter().position(|x| x == n).unwrap()] = format!("*p{k}");
                            guard(k, m);
                        }
                        Seg::Rest(n) => {
                            pat.push(format!("p{k} @ .."));
                            values[names.iter().position(|x| x == n).unwrap()] =
                                format!("::wisp::rt::rest(path, p{k})");
                        }
                    }
                }
                let guards: String = guards.iter().map(|g| format!(" && {g}")).collect();
                self.line(2, "{");
                self.line(3, "let mut segs = [\"\"; ::wisp::rt::MAX_SEGS];");
                self.line(
                    3,
                    &format!(
                        "if let Some([{}]) = ::wisp::rt::split(path, &mut segs){guards} {{ {} }} {pattern}",
                        pat.join(", "),
                        end.replace('@', &values.join(", "))
                    ),
                );
                self.line(2, "}");
                continue;
            }
            // Each segment in turn from `r`, what follows a `/`: the
            // static ones run together into one prefix.
            let mut steps = Vec::new();
            let mut prefix = String::new();
            let last = exp.len() - 1;
            for (k, seg) in exp.iter().enumerate() {
                match seg {
                    Seg::Static(s) if k < last => prefix.push_str(&(encode_path(s) + "/")),
                    Seg::Static(s) => {
                        prefix.push_str(&encode_path(s));
                        steps.push(format!("if r != {} {{ break 'a{a}; }}", lit(&prefix)));
                        prefix.clear();
                    }
                    Seg::Param(n, m) | Seg::Optional(n, m) => {
                        if !prefix.is_empty() {
                            steps.push(format!(
                                "let Some(r) = r.strip_prefix({}) else {{ break 'a{a}; }};",
                                lit(&prefix)
                            ));
                            prefix.clear();
                        }
                        let after = if k < last { "Some(r)" } else { "None" };
                        steps.push(format!(
                            "let (p{k}, {after}) = ::wisp::rt::seg(r) else {{ break 'a{a}; }};"
                        ));
                        values[names.iter().position(|x| x == n).unwrap()] = format!("p{k}");
                        guard(k, m);
                    }
                    Seg::Rest(_) => unreachable!("arms with one are matched above"),
                }
            }
            for g in &guards {
                steps.push(format!("if !({g}) {{ break 'a{a}; }}"));
            }
            self.line(2, &format!("'a{a}: {{ {pattern}"));
            self.line(3, "let r = r0;");
            for s in steps {
                self.line(3, &s);
            }
            self.line(3, &end.replace('@', &values.join(", ")));
            self.line(2, "}");
        }
        self.line(2, "None");
        self.line(1, "}");
        self.line(0, "");
    }

    /// `App::ROUTES`: every fact the server looks up by route id, a row a
    /// route, so none can drift from the others. `now` is whether a
    /// request is answered without waiting, decided here so the server
    /// pays nothing to know: when `before` in hooks.rs cannot wait and the
    /// model says the route cannot (`Model::route_waits`). Every doubt
    /// counts as waiting: a route wrongly `now` would fail its request
    /// (see `wisp::http::on_driver`).
    pub(super) fn routes(&mut self, p: &Project, assets: &Assets) {
        let m = &p.model;
        let before = p.before_waits;
        self.line(1, "const ROUTES: &'static [::wisp::rt::RouteFacts] = &[");
        for (r, route) in p.tree.routes.iter().zip(&m.routes) {
            let names: Vec<String> = r.params().iter().map(|p| lit(p)).collect();
            let limit = (route.body_limit.as_ref()).map(|m| format!("{m}::__call::BODY_LIMIT"));
            let uploads = (route.uploads.as_ref()).map(|m| format!("{m}::__call::UPLOADS"));
            let some = |x: Option<String>| x.map_or("None".into(), |x| format!("Some({x})"));
            // An embedded file at one of its paths is served before it.
            let files = (assets.files.iter())
                .any(|(url, ..)| r.expansions().iter().any(|e| may_match(e, url)));
            let sync: Vec<String> = (now_arms(p, route).iter())
                .flat_map(|(_, h)| method_of(h).1.split(" | "))
                .map(|v| format!("::wisp::Method::{v}.bit()"))
                .collect();
            let sync = if sync.is_empty() {
                "0".into()
            } else {
                sync.join(" | ")
            };
            self.line(
                2,
                &format!(
                    "::wisp::rt::RouteFacts {{ params: &[{}], body_limit: {}, uploads: {}, now: {}, sync: {sync}, files: {files}, error: {}, page: {}, pattern: {} }},",
                    names.join(", "),
                    some(limit),
                    some(uploads),
                    !before && !m.route_waits(route),
                    opt(route.error),
                    route.page.is_some(),
                    lit(&route.pattern)
                ),
            );
        }
        self.line(1, "];");
        // An unmatched path is answered by the root error page.
        // A `#[remote]` function is served where no route is, and may wait.
        if !before && !m.root_waits() && p.remotes.is_empty() {
            self.line(1, "const NOT_FOUND_NOW: bool = true;");
        }
        // Where only endpoints are, an unmatched path's error is JSON too.
        let ends = |r: &model::Route| {
            r.page.is_none() && r.server.as_ref().is_some_and(|s| !s.handlers.is_empty())
        };
        if p.remotes.is_empty() && !m.routes.is_empty() && m.routes.iter().all(ends) {
            self.line(1, "const API_ONLY: bool = true;");
        } else {
            let first = |r: &model::Route| {
                let seg = r.pattern.trim_start_matches('/').split('/').next();
                seg.filter(|s| !s.is_empty() && !s.starts_with(['[', '*']))
                    .map(str::to_string)
            };
            let mut prefixes: Vec<String> = Vec::new();
            for r in &m.routes {
                if let Some(s) = first(r)
                    && ends(r)
                    && m.routes
                        .iter()
                        .all(|o| first(o) != Some(s.clone()) || ends(o))
                    && !prefixes.contains(&s)
                {
                    prefixes.push(s);
                }
            }
            if !prefixes.is_empty() {
                let list: Vec<String> = prefixes.iter().map(|s| lit(s)).collect();
                self.line(
                    1,
                    &format!(
                        "const API_PREFIXES: &'static [&'static str] = &[{}];",
                        list.join(", ")
                    ),
                );
            }
        }
        // No source file of the app (tests too) names `trailing_slash`: no
        // request looks.
        if !mentions_slash(p.root) {
            self.line(1, "const TRAILING_SLASH: bool = false;");
        }
        // `after` and `report` in `src/hooks.rs`: the server calls them only
        // when these say so (consts, so an app without them has no check).
        // `before` is only said: its call is in `handle`.
        for name in ["before", "after", "report", "reroute"] {
            if p.has_hook(name) {
                self.line(1, &format!("const {}: bool = true;", name.to_uppercase()));
                if name == "before" {
                    continue;
                }
                if name == "reroute" {
                    self.line(
                        1,
                        "fn reroute(path: &str) -> &str { hooks::__call::reroute(path) }",
                    );
                    continue;
                }
                let (sig, args) = match name {
                    "after" => ("reply: &mut ::wisp::Reply", "cx, reply"),
                    _ => ("err: &::wisp::Error", "cx, err"),
                };
                self.line(
                    1,
                    &format!(
                        "fn {name}(cx: &mut ::wisp::Cx, {sig}) {{ hooks::__call::{name}({args}) }}"
                    ),
                );
            }
        }
    }

    /// The OpenAPI document and TypeScript client of the `+server.rs`
    /// endpoints, and the pages and their actions the document adds; the
    /// client and the document come back (empty without any).
    pub(super) fn api(&mut self, p: &Project) -> Result<(String, String), String> {
        // Types an endpoint names but does not define may be in the app's own
        // modules (`src/models.rs`).
        let shared = &p.shared;
        let (bearer, session, writes) = hooks_gate(p.root);
        let mut types: Vec<(&crate::routes::Route, Vec<Op>, Vec<rust_scan::TypeItem>)> =
            (p.tree.routes.iter().zip(&p.model.routes))
                .filter_map(|(route, r)| {
                    let server = r.server.as_ref()?;
                    // A route and its `/[id]` share the file: each answers its own.
                    let ops = (server.handlers.iter())
                        .filter(|h| h.member == route.member)
                        .map(|h| h.op.clone())
                        .collect();
                    let types = server.types.iter().chain(shared).cloned().collect();
                    Some((route, ops, types))
                })
                .collect();
        for op in types.iter_mut().flat_map(|(_, ops, _)| ops) {
            let gated = !writes || op.method != "get";
            op.bearer |= bearer && gated;
            op.session |= session && gated;
        }
        let endpoints: Vec<crate::openapi::Endpoint> = (types.iter())
            .map(|(route, ops, types)| crate::openapi::Endpoint { route, ops, types })
            .collect();
        let mut actions: Vec<(&crate::routes::Route, Vec<crate::openapi::Action>)> =
            (p.tree.routes.iter().zip(&p.model.routes))
                .filter(|(route, _)| !route.member)
                .filter_map(|(route, r)| {
                    let page = r.page.as_ref()?;
                    Some((
                        route,
                        page.actions().map(crate::openapi::Action::of).collect(),
                    ))
                })
                .collect();
        for a in actions.iter_mut().flat_map(|(_, actions)| actions) {
            a.bearer |= bearer;
            a.session |= session;
        }
        if endpoints.is_empty() && actions.iter().all(|(_, a)| a.is_empty()) {
            return Ok((String::new(), String::new()));
        }
        let pages: Vec<crate::openapi::Page> = (actions.iter())
            .map(|(route, actions)| crate::openapi::Page {
                route,
                actions,
                types: shared,
            })
            .collect();
        let client = crate::openapi::typescript(&endpoints);
        if !endpoints.is_empty() {
            self.line(1, "fn client_ts() -> &'static str {");
            self.line(2, &lit(&client));
            self.line(1, "}");
        }
        // Cargo.toml, so `wisp openapi` and the build agree; Cargo's own
        // for what it inherits from the workspace (`version.workspace`).
        let toml = fs::read_to_string(p.root.join("Cargo.toml")).unwrap_or_default();
        let package = |key: &str, or: &str| {
            package_field(&toml, key)
                .or_else(|| std::env::var(format!("CARGO_PKG_{}", key.to_uppercase())).ok())
                .unwrap_or_else(|| or.into())
        };
        let (name, version) = (package("name", "app"), package("version", "0.1.0"));
        let spec = crate::openapi::spec(&name, &version, &endpoints, &pages);
        self.line(1, "fn openapi() -> &'static str {");
        self.line(2, &lit(&spec));
        self.line(1, "}");
        self.line(0, "");
        Ok((client, spec))
    }

    pub(super) fn init(&mut self, p: &Project) {
        self.line(1, "async fn init() -> ::wisp::Result<()> {");
        if let Some(l) = &p.i18n {
            self.line(2, &l.config());
        }
        // What `#[derive(Config)]` reads is there for `init`.
        let mods = p.mods.iter().map(|m| (m, "__mods::"));
        let own = p.hooks.iter().chain(&p.user_mods).map(|m| (m, ""));
        for (m, at) in mods.chain(own) {
            if !m.configs.is_empty() {
                self.line(2, &format!("{at}{}::__call::__config()?;", m.name));
            }
        }
        if p.has_hook("init") {
            self.line(2, "hooks::__call::init().await?;");
        }
        // Saved tables load now, once `init` has set the store: nothing lists
        // them at run time, and a store that fails stops the server here.
        let mods = p.mods.iter().map(|m| (m, "__mods::"));
        let own = p.hooks.iter().chain(&p.user_mods).map(|m| (m, ""));
        for (m, at) in mods.chain(own) {
            if !m.tables.is_empty() {
                self.line(2, &format!("{at}{}::__call::__ready();", m.name));
            }
        }
        self.line(2, "Ok(())");
        self.line(1, "}");
        self.line(0, "");
    }

    /// The pages `wisp build` prerendered, as `static PRE_{route}_{k}`
    /// responses (see `Baked`); per route, the paths of its `k`s.
    pub(super) fn prerendered(&mut self, p: &Project) -> Result<Vec<Vec<String>>, String> {
        let mut pre = vec![Vec::new(); p.model.routes.len()];
        let Some(dir) = p.prerendered else {
            return Ok(pre);
        };
        let at = |e: std::io::Error| format!("{}: {e}", dir.display());
        let index = std::fs::read_to_string(dir.join("index.tsv")).map_err(at)?;
        for line in index.lines() {
            let mut parts = line.split('\t');
            let (Some(pattern), Some(path), Some(name)) =
                (parts.next(), parts.next(), parts.next())
            else {
                continue;
            };
            let Some(i) = (p.model.routes.iter()).position(|r| {
                r.pattern == pattern && r.page.as_ref().is_some_and(|pg| pg.prerender)
            }) else {
                continue;
            };
            let file = dir.join(name);
            let doc = std::fs::read_to_string(&file).map_err(at)?;
            let etag = format!("\"{:016x}\"", fnv1a(doc.as_bytes()));
            let head = format!(
                "HTTP/1.1 200 OK\r\ncontent-type: text/html; charset=utf-8\r\netag: {etag}\r\ncontent-length: {}\r\n",
                doc.len()
            );
            self.line(
                0,
                &format!(
                    "static PRE_{i}_{}: ::wisp::rt::Baked = ::wisp::rt::Baked::new({}, include_str!({}), {}); // {path}",
                    pre[i].len(),
                    lit(&head),
                    lit(&file.to_string_lossy()),
                    lit(&etag),
                ),
            );
            pre[i].push(path.to_string());
        }
        Ok(pre)
    }

    pub(super) fn handle(&mut self, p: &Project, baked: &[Option<String>], pre: &[Vec<String>]) {
        self.line(1, "async fn handle(route: Option<usize>, cx: &mut ::wisp::Cx, __o: &mut ::wisp::Out) -> ::wisp::Result<()> {");
        self.line(2, "use ::wisp::Method::*;");
        if p.has_hook("before") {
            self.line(2, "// src/hooks.rs");
            self.line(2, &answer("hooks::__call::before"));
        }
        self.line(2, "::wisp::rt::hooked(cx);");
        let unrouted = match p.remotes.is_empty() {
            true => "Err(::wisp::Error::new(404, \"Not Found\"))",
            false => "serve_remote(cx, __o).await",
        };
        self.line(
            2,
            &format!("let Some(route) = route else {{ return {unrouted} }};"),
        );
        self.line(2, "match (route, cx.method) {");
        for (i, r) in p.model.routes.iter().enumerate() {
            let mut allow: Vec<&str> = Vec::new();
            self.line(3, &format!("// {}", r.pattern));
            // A GET's statements, when `CACHE` keeps it: what this worker
            // has, or else what `serve` answers, kept (apart per `accept`
            // when the answer varies by it).
            let kept = |serve: String| match &r.cache {
                Some(c) => {
                    let (m, public) = (&c.module, c.public);
                    let by = r.by_accept();
                    format!(
                        "if ::wisp::rt::cached::<{by}>(cx, __o, {public}) {{ return Ok(()); }} {serve} \
                         ::wisp::rt::keep::<Self, {by}>(cx, __o, {m}::__call::CACHE, {public}, {m}::__call::MORE);"
                    )
                }
                None => serve,
            };
            if let Some(page) = &r.page {
                let get = match baked[i] {
                    Some(_) => format!(
                        "if ::wisp::rt::baked(cx, __o, &BAKED_{i}) {{ Ok(()) }} else {{ serve_page_{i}(cx, __o).await }}"
                    ),
                    None if r.cache.is_some() => {
                        format!(
                            "{{ {} Ok(()) }}",
                            kept(format!("serve_page_{i}(cx, __o).await?;"))
                        )
                    }
                    None => format!("serve_page_{i}(cx, __o).await"),
                };
                // What `wisp build` prerendered, by path.
                let get = match pre[i].is_empty() {
                    true => get,
                    false => {
                        let arms: String = (pre[i].iter().enumerate())
                            .map(|(k, path)| format!("{} => Some(&PRE_{i}_{k}), ", lit(path)))
                            .collect();
                        format!(
                            "if let Some(b) = match cx.path() {{ {arms}_ => None }} {{ \
                             if ::wisp::rt::baked(cx, __o, b) {{ return Ok(()); }} }} {get}"
                        )
                    }
                };
                // live.js asks for the page's error page this way when its
                // browser code fails while starting (see `boundary` in
                // live.js): only pages have any.
                let layouts = r.layouts.iter().filter(|l| p.model.layouts[**l].guard);
                let mut guard: String = layouts
                    .map(|l| format!("layout_{l}::__call::__guard(cx)?; "))
                    .collect();
                if let Some(g) = &r.guard {
                    guard.push_str(&format!("{g}::__call::__guard(cx)?; "));
                }
                let (open, close) = within(r, &page.module);
                // A guard (a rate limit, a check, a middleware) runs for every
                // request: the edge build's table of constant answers must not
                // skip it.
                let note = match guard.is_empty() {
                    true => "",
                    false => "#[cfg(target_arch = \"wasm32\")] ::wisp::rt::guarded(cx); ",
                };
                self.line(
                    3,
                    &format!("({i}, Get | Head) => {open}{{ {note}{guard}::wisp::rt::browser_ok(cx)?; {get} }}{close},"),
                );
                allow.extend(["GET", "HEAD"]);
                let actions: Vec<&FnItem> = page.actions().collect();
                if !actions.is_empty() {
                    self.line(3, &format!("({i}, Post) => {open}{{"));
                    self.line(4, &guard);
                    self.line(4, "::wisp::rt::check_origin(cx)?;");
                    self.line(4, "match cx.action() {");
                    // `invalid(field, ..)` shows the page again, as a 422, with
                    // what is wrong for `cx.problem(field)`.
                    for a in &actions {
                        self.line(
                            5,
                            &format!(
                                "{} => match {}::__call::{}(cx).await {{ \
                                 Ok(Some(r)) => {{ ::wisp::rt::respond(__o, r); return Ok(()); }} \
                                 Ok(None) => {{}} \
                                 Err(e) => ::wisp::rt::input::failed(cx, e)?, }},",
                                lit(&a.name),
                                page.module,
                                a.name
                            ),
                        );
                    }
                    self.line(5, "other => return Err(::wisp::rt::no_action(other)),");
                    self.line(4, "}");
                    self.line(4, &format!("serve_page_{i}(cx, __o).await"));
                    self.line(3, &format!("}}{close},"));
                    allow.push("POST");
                }
            }
            for (s, h) in (r.server.iter()).flat_map(|s| s.handlers.iter().map(move |h| (s, h))) {
                let (_, variants, allowed) = method_of(h);
                let m = &s.module;
                let before = match s.before {
                    true => answer(&format!("{m}::__call::before")) + " ",
                    false => String::new(),
                };
                let mut serve = serve(m, h, &format!("{}(cx).await", h.shim));
                if h.op.method == "get" {
                    serve = kept(serve);
                }
                let (open, close) = within(r, m);
                let csrf = match s.csrf && h.op.method != "get" {
                    true => "::wisp::rt::check_origin(cx)?; ",
                    false => "",
                };
                self.line(
                    3,
                    &format!("({i}, {variants}) => {open}{{ ::wisp::rt::endpoint(cx); {csrf}{before}{serve} Ok(()) }}{close}{}", if open.is_empty() { "" } else { "," }),
                );
                allow.push(allowed);
            }
            // OPTIONS says what the route takes; CORS preflights are answered
            // by `cx.cors` in `before`, which runs first.
            allow.push("OPTIONS");
            let allow = lit(&allow.join(", "));
            self.line(
                3,
                &format!("({i}, Options) => {{ ::wisp::rt::respond(__o, ::wisp::rt::options({allow})); Ok(()) }}"),
            );
            // An endpoint's errors are JSON, whatever its path.
            let api =
                match r.page.is_some() || r.server.as_ref().is_none_or(|s| s.handlers.is_empty()) {
                    true => "",
                    false => "::wisp::rt::endpoint(cx); ",
                };
            self.line(
                3,
                &format!("({i}, _) => {{ {api}Err(::wisp::rt::method_not_allowed({allow})) }}"),
            );
        }
        self.line(3, "_ => Err(::wisp::Error::new(404, \"Not Found\")),");
        self.line(2, "}");
        self.line(1, "}");
        self.line(0, "");
    }

    /// `handle`'s arms that are sync (see `now_arms`), as plain code:
    /// `Ok(false)` for any other, which `handle` answers.
    pub(super) fn handle_now(&mut self, p: &Project) {
        let arms: Vec<(usize, &model::Route)> = (p.model.routes.iter().enumerate())
            .filter(|(_, r)| !now_arms(p, r).is_empty())
            .collect();
        if arms.is_empty() {
            return;
        }
        self.line(1, "fn handle_now(route: Option<usize>, cx: &mut ::wisp::Cx, __o: &mut ::wisp::Out) -> ::wisp::Result<bool> {");
        self.line(2, "use ::wisp::Method::*;");
        self.line(2, "let Some(route) = route else { return Ok(false) };");
        self.line(2, "match (route, cx.method) {");
        for (i, r) in arms {
            for (s, h) in now_arms(p, r) {
                let mut serve = serve(&s.module, h, &format!("{}_now(cx)", h.shim));
                if let (Some(c), "get") = (&r.cache, h.op.method) {
                    let (m, public, by) = (&c.module, c.public, r.by_accept());
                    serve = format!(
                        "if ::wisp::rt::cached::<{by}>(cx, __o, {public}) {{ return Ok(true); }} {serve} \
                         ::wisp::rt::keep::<Self, {by}>(cx, __o, {m}::__call::CACHE, {public}, {m}::__call::MORE);"
                    );
                }
                self.line(
                    3,
                    &format!(
                        "({i}, {}) => {{ ::wisp::rt::hooked(cx); ::wisp::rt::endpoint(cx); {serve} Ok(true) }}",
                        method_of(h).1
                    ),
                );
            }
        }
        self.line(3, "_ => Ok(false),");
        self.line(2, "}");
        self.line(1, "}");
        self.line(0, "");
    }

    /// The nearest error page per route; unmatched URLs use the root one.
    pub(super) fn error(&mut self, p: &Project) {
        let m = &p.model;
        self.line(1, "async fn error(route: Option<usize>, cx: &mut ::wisp::Cx, __o: &mut ::wisp::Out, status: u16, message: &str) -> ::wisp::Result<()> {");
        if p.i18n.is_some() {
            self.line(2, "__o.lang = ::wisp::rt::pick_locale(cx);");
        }
        if m.errors.is_empty() {
            self.line(2, "let _ = route;");
            self.line(2, "::wisp::rt::default_error(cx, __o, status, message);");
            self.line(2, "Ok(())");
        } else {
            self.line(
                2,
                &format!(
                    "let page = match route {{ Some(r) => Self::ROUTES[r].error, None => {} }};",
                    opt(m.root_error)
                ),
            );
            self.line(2, "match page {");
            for i in 0..m.errors.len() {
                self.line(
                    3,
                    &format!("Some({i}) => serve_error_{i}(cx, __o, status, message).await,"),
                );
            }
            self.line(
                3,
                "_ => { ::wisp::rt::default_error(cx, __o, status, message); Ok(()) }",
            );
            self.line(2, "}");
        }
        self.line(1, "}");
    }
}
