//! `wisp_build::run`, as an app's `build.rs` calls it: in a process of its
//! own, told where the app and `OUT_DIR` are by the environment.

use crate::common::Project;
use std::fs;
use std::path::Path;
use std::process::{Command, Output};

/// Set in the processes these tests start, so `child` knows to be one.
const CHILD: &str = "WISP_BUILD_TEST_CHILD";

/// Not a test of its own: it is what the tests below run in a new process.
/// Started by anyone else it does nothing.
#[test]
fn child() {
    if std::env::var_os(CHILD).is_some() {
        wisp_build::run();
    }
}

/// Runs `wisp_build::run` with `CARGO_MANIFEST_DIR`, `OUT_DIR` and `PROFILE`
/// as given, or not set.
fn build(root: Option<&Path>, out: Option<&Path>, profile: Option<&str>) -> Output {
    let mut cmd = Command::new(std::env::current_exe().unwrap());
    cmd.args(["run::child", "--exact", "--nocapture", "--test-threads=1"])
        .env(CHILD, "1")
        .env_remove("CARGO_MANIFEST_DIR")
        .env_remove("OUT_DIR")
        .env_remove("PROFILE");
    if let Some(p) = root {
        cmd.env("CARGO_MANIFEST_DIR", p);
    }
    if let Some(p) = out {
        cmd.env("OUT_DIR", p);
    }
    if let Some(p) = profile {
        cmd.env("PROFILE", p);
    }
    cmd.output().unwrap()
}

fn text(bytes: &[u8]) -> String {
    String::from_utf8_lossy(bytes).into_owned()
}

fn app() -> Project {
    Project::new(&[
        (
            "src/routes/+page.wisp",
            "<h1>home</h1>\n<p>text {1 + 1}</p>",
        ),
        ("src/routes/blog/[slug]/+page.wisp", "{slug}"),
        (
            "src/routes/api/+server.rs",
            "#[derive(Json)]\nstruct Note { title: String }\nfn get() -> Vec<Note> { Vec::new() }",
        ),
        ("src/app.css", "body { margin: 0 }"),
        ("static/robots.txt", "User-agent: *"),
        ("static/img/a b.SVG", "<svg/>"),
    ])
}

#[test]
fn a_build_script_writes_the_app() {
    let project = app();
    let out = Project::new(&[]);
    let wisp_rs = out.root().join("wisp.rs");
    let run = build(Some(project.root()), Some(out.root()), None);
    assert!(run.status.success(), "{}", text(&run.stderr));
    let stdout = text(&run.stdout);
    for line in [
        "cargo::rerun-if-changed=src",
        "cargo::rerun-if-changed=static",
    ] {
        assert!(stdout.contains(line), "{line} in {stdout}");
    }
    // `.wisp/app.css` does not exist, so Cargo is not told to watch it.
    assert!(!stdout.contains("app.css"), "{stdout}");
    let code = fs::read_to_string(&wisp_rs).unwrap();
    for want in [
        "@generated by wisp-build",
        "// /blog/[slug]",
        "impl ::wisp::App for App",
        "const CSS: Option<&'static str> = Some(\"dev\");",
        "fn openapi() -> &'static str",
    ] {
        assert!(code.contains(want), "{want} in {code}");
    }
    // A dev build reads its assets from disk.
    assert!(!code.contains("ASSET_0"), "{code}");
    assert!(!code.contains("\"text 2\""), "{code}");

    // The same app again does not touch the file: its modified time stays
    // as it was set, long ago, or Cargo would rebuild the app every time.
    let long_ago = std::time::UNIX_EPOCH;
    let file = fs::File::options().write(true).open(&wisp_rs).unwrap();
    file.set_modified(long_ago).unwrap();
    drop(file);
    let again = build(Some(project.root()), Some(out.root()), None);
    assert!(again.status.success(), "{}", text(&again.stderr));
    assert_eq!(
        fs::metadata(&wisp_rs).unwrap().modified().unwrap(),
        long_ago
    );
    assert_eq!(fs::read_to_string(&wisp_rs).unwrap(), code);

    // Another app does.
    fs::write(
        project.root().join("src/routes/+page.wisp"),
        "<h1>changed</h1>",
    )
    .unwrap();
    let changed = build(Some(project.root()), Some(out.root()), None);
    assert!(changed.status.success(), "{}", text(&changed.stderr));
    assert_ne!(fs::read_to_string(&wisp_rs).unwrap(), code);
}

#[test]
fn a_release_build_bakes_in_the_static_files() {
    let project = app();
    let out = Project::new(&[]);
    let run = build(Some(project.root()), Some(out.root()), Some("release"));
    assert!(run.status.success(), "{}", text(&run.stderr));
    let code = fs::read_to_string(out.root().join("wisp.rs")).unwrap();
    for want in [
        // The CSS, then the files of `static`, sorted, by their URLs, in a
        // table sorted to be searched.
        "static BY_PATH: [(&str, &::wisp::Asset); 3] = [(\"/_app/app.css\", &ASSET_0), \
         (\"/img/a%20b.SVG\", &ASSET_1), (\"/robots.txt\", &ASSET_2)];",
        "BY_PATH.binary_search_by(",
        "ext: \"svg\"",
        "ext: \"txt\"",
        "ext: \"css\"",
        "include_bytes!(",
        "Some(\"",
        "\"<h1>home</h1>",
        "tpl_shell::S\n",
    ] {
        assert!(code.contains(want), "{want} in {code}");
    }
    assert!(!code.contains("Some(\"dev\")"), "{code}");
    // Other profiles are dev builds.
    let out = Project::new(&[]);
    let run = build(Some(project.root()), Some(out.root()), Some("debug"));
    assert!(run.status.success(), "{}", text(&run.stderr));
    let code = fs::read_to_string(out.root().join("wisp.rs")).unwrap();
    assert!(code.contains("Some(\"dev\")"), "{code}");
}

/// Scoped styles follow the app's CSS: written whole into a release build,
/// to `.wisp/scoped.css` by a dev one (and by `wisp dev`, which says when
/// they changed).
#[test]
fn scoped_styles_join_the_apps_css() {
    let project = Project::new(&[
        (
            "src/routes/+page.wisp",
            "<h1>a</h1><style>h1 { x: 1 }</style>",
        ),
        (
            "src/components/Card.wisp",
            "<b>b</b>\n<style>b { y: 2 }</style>",
        ),
        ("src/app.css", "body { margin: 0 }"),
    ]);
    let (page, card) = (
        wisp_build::style::class("src/routes/+page.wisp"),
        wisp_build::style::class("src/components/Card.wisp"),
    );
    let out = Project::new(&[]);
    let run = build(Some(project.root()), Some(out.root()), Some("release"));
    assert!(run.status.success(), "{}", text(&run.stderr));
    let code = fs::read_to_string(out.root().join("wisp.rs")).unwrap();
    let css = format!("body {{ margin: 0 }}\\nb.{card} {{ y: 2 }}\\nh1.{page} {{ x: 1 }}");
    assert!(
        code.contains(&format!("body: \"{css}\".as_bytes()")),
        "{code}"
    );
    assert!(
        code.contains(&format!("<h1 class=\\\"{page}\\\">a</h1>")),
        "{code}"
    );
    let scoped = project.root().join(".wisp/scoped.css");
    assert!(!scoped.exists());

    let run = build(Some(project.root()), Some(out.root()), None);
    assert!(run.status.success(), "{}", text(&run.stderr));
    let dev = format!("b.{card} {{ y: 2 }}\nh1.{page} {{ x: 1 }}");
    assert_eq!(fs::read_to_string(&scoped).unwrap(), dev);
    assert_eq!(wisp_build::write_styles(project.root()), Ok((false, true)));
    fs::write(project.root().join("src/routes/+page.wisp"), "<h1>a</h1>").unwrap();
    assert_eq!(wisp_build::write_styles(project.root()), Ok((true, true)));
    fs::write(project.root().join("src/components/Card.wisp"), "<b>b</b>").unwrap();
    assert_eq!(wisp_build::write_styles(project.root()), Ok((true, false)));
    assert_eq!(fs::read_to_string(&scoped).unwrap(), "");
}

/// Accessibility lints warn, from `check` and from the build (unless the
/// CLI, which checked first, runs it); they never stop it.
#[test]
fn lints_are_warnings() {
    let project = Project::new(&[("src/routes/+page.wisp", "<h1>a</h1>\n<img src=\"a.png\">")]);
    let want = "src/routes/+page.wisp:2: <img> has no alt";
    let (_, warnings) = wisp_build::check(project.root()).unwrap();
    assert!(
        warnings.len() == 1 && warnings[0].starts_with(want),
        "{warnings:?}"
    );
    assert!(warnings[0].ends_with("(a11y-img-alt)"), "{warnings:?}");
    let out = Project::new(&[]);
    let run = build(Some(project.root()), Some(out.root()), None);
    assert!(run.status.success(), "{}", text(&run.stderr));
    let stdout = text(&run.stdout);
    assert!(
        stdout.contains(&format!("cargo::warning={want}")),
        "{stdout}"
    );
}

#[test]
fn a_mistake_ends_the_build_with_its_message() {
    let project = Project::new(&[("src/routes/about/page.wisp", "x")]);
    let out = Project::new(&[]);
    let run = build(Some(project.root()), Some(out.root()), None);
    assert_eq!(run.status.code(), Some(1));
    let stderr = text(&run.stderr);
    assert!(
        stderr.contains("wisp: src/routes/about/page.wisp: route files start with `+`"),
        "{stderr}"
    );
    assert!(!out.root().join("wisp.rs").exists());
}

#[test]
fn a_build_script_needs_cargos_environment() {
    let project = app();
    let out = Project::new(&[]);
    let run = build(None, Some(out.root()), None);
    assert!(!run.status.success());
    assert!(
        text(&run.stderr).contains("wisp_build::run must be called from build.rs"),
        "{}",
        text(&run.stderr)
    );
    let run = build(Some(project.root()), None, None);
    assert!(!run.status.success());
    assert!(
        text(&run.stderr).contains("wisp_build::run must be called from build.rs"),
        "{}",
        text(&run.stderr)
    );
}

#[test]
fn a_tailwind_stylesheet_without_its_build_warns() {
    let project = Project::new(&[
        ("src/routes/+page.wisp", "x"),
        ("src/app.css", "@import \"tailwindcss\";"),
    ]);
    let out = Project::new(&[]);
    let run = build(Some(project.root()), Some(out.root()), None);
    assert!(run.status.success(), "{}", text(&run.stderr));
    assert!(
        text(&run.stdout)
            .contains("cargo::warning=src/app.css uses Tailwind but .wisp/app.css is missing"),
        "{}",
        text(&run.stdout)
    );
    // With its build there is nothing to say, and Cargo watches it.
    fs::create_dir_all(project.root().join(".wisp")).unwrap();
    fs::write(project.root().join(".wisp/app.css"), "a{}").unwrap();
    let run = build(Some(project.root()), Some(out.root()), None);
    assert!(run.status.success(), "{}", text(&run.stderr));
    let stdout = text(&run.stdout);
    assert!(!stdout.contains("warning"), "{stdout}");
    assert!(
        stdout.contains("cargo::rerun-if-changed=.wisp/app.css"),
        "{stdout}"
    );
}
